[package]
name = "md-shelf-bg"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
pulldown-cmark = "0.13.0"
tokio = { version = "1.47.1", features = ["full"] }